config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get '/about', to: 'static_pages#about'

  resources :users, only: [:new, :index, :create]

  resources :sessions, only: [:new, :create, :destroy]
  get    'login',  to: 'sessions#new'
  delete 'logout', to: "sessions#destroy"

  resources :categories, only: [:index, :show, :new, :create] do
    resources :playspaces, only: :index
  end

  resources :playspaces, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:new, :index, :create]
  end

  resources :bookmarks, only: [:index, :create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 top-margin">

  <h2>About</h2>

    <p>This app is for parents who are searching for outdoor spaces including playgrounds, parks and beaches in Hong Kong.</p>

    <p>With energy levels higher than the sun, the small humans in your care need to roam free. That's great as long as you can find a playground or park that suits you.</p>

    <p>But what if you could ask other parents for their recommendation? That's why PlaySpace only has reviews submitted by the people who use these playspaces: <strong>you</strong>.</p>

    <p> Please help us to make PlaySpace even better by becoming a member of the site and adding your local playspace, and reviewing playspaces added by other users.</p>

    <p>So, we hope you like the app and have a lot of fun exploring with your children.</p>
</div>

<script>HideSearchToggle()</script>

app/views/static_pages/home.html.erb
<header class="header">
  <!-- background image goes in here. see static_pages.scss -->
  <div class="container">
    <div class="intro-text">
      <div class="intro-heading">Find your next PLAY SPACE</div>
      <%= link_to "GO!", playspaces_path, class: "page-scroll btn btn-xl" %>
    </div>
  </div>

</header>

<script>HideSearchToggle()</script>