config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get '/about', to: 'static_pages#about'

  resources :users, only: [:new, :index, :create]

  resources :sessions, only: [:new, :create, :destroy]
  get    'login',  to: 'sessions#new'
  delete 'logout', to: "sessions#destroy"

  resources :categories, only: [:index, :show, :new, :create] do
    resources :playspaces, only: :index
  end

  resources :playspaces, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:new, :index, :create]
  end

  resources :bookmarks, only: [:index, :create, :destroy]
end

app/models/playspace.rb
class Playspace < ActiveRecord::Base
  belongs_to :category

  has_many :reviews
  has_many :bookmarks

  before_validation :format_values

  validates :name, presence: true
  validates :region, presence: true
  validates :district, presence: true
  validates :category, presence: true

  def format_values
    self[:name] = self[:name].downcase if self[:name].present?
    self[:region] = self[:region].downcase if self[:region].present?
    self[:district] = self[:district].downcase if self[:district].present?
    self[:category] = self[:category].downcase if self[:category].present?
  end

  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "DSC_0028.jpg"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

end

app/controllers/playspaces_controller.rb
class PlayspacesController < ApplicationController
  before_action :set_category

  def index
    if @category
      @playspaces = filter_queries(@category.playspaces)
    else
      @playspaces = filter_queries
    end
  end

  def show
    @playspace = Playspace.find(params[:id])
    @features = ["bike_path", "merry_go_round", "play_structure", "seesaw", "slide", "swing", "carpark", "snack_shop" "wc"]
  end

  def new
    @playspace = Playspace.new
    @categories = Category.all
  end

  def create
    @playspace = Playspace.new(playspaces_params)
    if @playspace.save
      redirect_to playspace_path(@playspace.id)
    else
      render :new
    end
  end

  private
  def set_category
    @category = Category.find(params[:category_id]) if params[:category_id]
  end

  def playspaces_params
    params.require(:playspace).permit(:name, :address, :district, :region, :bike_path, :merry_go_round, :play_structure, :seesaw, :slide, :swing, :carpark, :snack_shop, :wc, :category_id, :photo)
  end

  def filter_params
    params.require(:playspace).permit(:name, :district, :region, :category_id, :bike_path, :merry_go_round, :play_structure, :seesaw, :slide, :swing, :carpark, :snack_shop, :wc)
  end

  def filter_queries(results=nil)
    require 'wannabe_bool'
    results = results || Playspace.all

    if params[:playspace] != nil
      puts "started Filtering"
      f_params        = filter_params
      name            = f_params[:name]         == nil || f_params[:name]         == "" ? nil : f_params[:name].downcase
      region          = f_params[:region]       == nil || f_params[:region]       == "" ? nil : f_params[:region].downcase
      district        = f_params[:district]     == nil || f_params[:district]     == "" ? nil : f_params[:district].downcase
      category_id     = f_params[:category_id]  == nil || f_params[:category_id]  == "" ? nil : f_params[:category_id].to_i
      bike_path       = f_params[:bike_path].to_b
      merry_go_round  = f_params[:merry_go_round].to_b
      play_structure  = f_params[:play_structure].to_b
      seesaw          = f_params[:seesaw].to_b
      slide           = f_params[:slide].to_b
      swing           = f_params[:swing].to_b
      carpark         = f_params[:carpark].to_b
      snack_shop      = f_params[:snack_shop].to_b
      wc              = f_params[:wc].to_b

      results = results.where("name LIKE ?", '%' + name +'%') if name != nil
      results = results.where(region: region)                 if region != nil
      results = results.where(district: district)             if district != nil
      results = results.where(category_id: category_id)       if category_id != nil
      results = results.where(bike_path: bike_path)           if bike_path
      results = results.where(merry_go_round: merry_go_round) if merry_go_round
      results = results.where(play_structure: play_structure) if play_structure
      results = results.where(seesaw: seesaw)                 if seesaw
      results = results.where(slide: slide)                   if slide
      results = results.where(swing: swing)                   if swing
      results = results.where(carpark: carpark)               if carpark
      results = results.where(snack_shop: snack_shop)         if snack_shop
      results = results.where(wc: wc)                         if wc

      return results
    else
      return results
    end
  end

end

app/helpers/playspaces_helper.rb
module PlayspacesHelper
  def features_list(playspace)
    @features = {
      bike_path: "bike.png",
      merry_go_round: "merrygoround.png",
      play_structure: "playstructure.png",
      seesaw: "seesaw.png",
      slide: "slide.png",
      swing: "swing.png",
      carpark: "carpark.png",
      snack_shop: "snack.png",
      wc: "wc.png"
    }
    @array = []
    @features.each do |feature, image|
      @array.push image if playspace[feature]
    end
  end
end

app/views/playspaces/_form.html.erb
<div class="row">
  <div class="col-xs-12">

    <%= bootstrap_form_for(@playspace) do |f| %>
      <div>
        <%= f.text_field :name %>
      </div>
      <div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, :prompt => 'Select') %>
      </div>
      <div>
        <%= f.select(:region, ["", "HK", "Kln", "NT"]) %>
      </div>
      <div>
        <%= f.select(:district, []) %>
      </div>
      <div>
        <%= f.text_field :address %>
      </div>
      <div>
        <%= f.file_field :photo %>
      </div>

    <div class="row">

      <div class ="col-lg-3 portfolio-item">
        <div>
          <%= f.check_box :bike_path %>
        </div>
        <div>
          <%= f.check_box :merry_go_round, label: "Merry-go-round" %>
        </div>
        <div>
          <%= f.check_box :play_structure %>
        </div>
      </div>

      <div class="col-lg-3 portfolio-item">
        <div>
          <%= f.check_box :seesaw %>
        </div>
        <div>
          <%= f.check_box :slide %>
        </div>
        <div>
          <%= f.check_box :swing %>
        </div>
      </div>

      <div class="col-lg-3 portfolio-item">
        <div>
          <%= f.check_box :carpark %>
        </div>
        <div>
          <%= f.check_box :snack_shop %>
        </div>
        <div>
          <%= f.check_box :wc, label: "Toilet" %>
        </div>
      </div>

      <div>
      <%= f.submit "Create Playspace", class: "btn btn-success btn-block no-margin" %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/playspaces/index.html.erb
<div class="top-margin" id="playspaces-index">
  <h2><%= @category.name.capitalize if @category %> Playspaces</h2>

  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
        <ul class="list-unstyled list-inline">
          <% if @playspaces.empty? %>
            <h1>No Results</h1>
          <% else %>
            <% @playspaces.each do |playspace| %>
              <li class="col-xs-6 col-lg-3 add-padding pull-left">
                <div class="playspace-photo">
                  <%= image_tag heroku_image_path(playspace.photo.path) %>
                </div>
                <div class="playspace-detail">
                  <span>
                    <%= avg_rating(playspace) %>
                  </span>
                  <br>
                  <span class="name"><%= link_to playspace.name.titleize, playspace_path(playspace) %></span>
                  <br>
                  <span class="district"><em><%= playspace.district.titleize %>, <%= playspace.region.upcase %></em></span>
                </div>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

<script>PlayspaceSidebar()</script>

app/views/playspaces/new.html.erb
<div class="container top-margin">
  <div class="row">

<div class="col-xs-12">
  <h2>Add a PlaySpace</h2>

  <%= render 'form' %>

</div>

  </div>
</div>

<script>HideSearchToggle()</script>

app/views/playspaces/show.html.erb
<div class="container top-margin" id="playspaces-show">

  <div class="row">
    <div class="col-xs-6 col-sm-4">
      <div>
        <%= image_tag @playspace.photo.url %>
      </div>
      <div>
        <%= avg_rating(@playspace) %>
      </div>
      <div><strong><%= @playspace.name.titleize %></strong></div>
      <div class="bottom-margin"><em><%= @playspace.district.titleize %>, <%= @playspace.region.upcase %></em></div>
      <div>Address: <%= @playspace.address.titleize %></div>
    </div>
    <div class="col-xs-6 col-sm-4">
      <%= form_for :bookmark, url: bookmarks_path do |f| %>
        <%= f.hidden_field :playspace_id, {value: @playspace.id} %>
        <%= f.submit "Bookmark", class: "btn btn-default" %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-6 col-sm-4 features">
      <h6>Features</h6>
      <span class="features-list"><% features_list(@playspace) %>
        <% @array.each do |image| %>
          <%= image_tag(image) %>
        <% end %>
      </span>
    </div>
    <div class="col-xs-6 col-sm-4">
      <%= link_to 'Reviews', playspace_reviews_path(@playspace.id), class: "btn btn-default" %>
    </div>
  </div>

</div>

<script>HideSearchToggle()</script>