config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get '/about', to: 'static_pages#about'

  resources :users, only: [:new, :index, :create]

  resources :sessions, only: [:new, :create, :destroy]
  get    'login',  to: 'sessions#new'
  delete 'logout', to: "sessions#destroy"

  resources :categories, only: [:index, :show, :new, :create] do
    resources :playspaces, only: :index
  end

  resources :playspaces, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:new, :index, :create]
  end

  resources :bookmarks, only: [:index, :create, :destroy]
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_playspace
  before_action :authenticate, only: :create

  def index
    @reviews = @playspace.reviews.reverse
    @review  = @playspace.reviews.new
  end

  def new
    @review = @playspace.reviews.new
  end

  def create
    @review = @playspace.reviews.new(reviews_params)
    @review.user = current_user
    @review.rating = @review.rating.to_i
    if @review.save
      redirect_to playspace_reviews_path(@playspace.id)
    else
      redirect_to playspace_reviews_path(@playspace.id)
    end
  end

  def edit
    @review = @playspace.review.find(reviews_params)
  end

  def update
    @revew = @playspace.review.find(reviews_params)
    if @review.update
      redirect_to playspace_reviews_path(@playspace.id)
    else
      render :edit
    end
  end

  private
  def set_playspace
    @playspace = Playspace.find(params[:playspace_id])
  end

  def reviews_params
    params.require(:review).permit(:comment, :rating, :photo)
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= bootstrap_form_for @review, url: playspace_reviews_path(@playspace.id), html: { multipart: true } do |f| %>
  <% if @review.errors.any? %>
  <div class="error_messages">
    <h2>Form is invalid</h2>
    <ul>
      <% for message in @review.errors.full_messages %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <%= f.text_field :comment, label: "Leave a Review" %>
  <%= f.file_field :photo %>
  <%= f.select :rating, [1, 2, 3, 4, 5] %>
  <%= f.submit class: "btn btn-default btn-block no-margin" %>

<% end %>

app/views/reviews/index.html.erb
<div class="container top-margin" id="reviews-index">

  <div class="row">
    <div class="col-xs-6 col-sm-4">
      <div>
        <%= avg_rating(@playspace) %>
      </div>
      <div><strong><%= @playspace.name.titleize %></strong></div>
      <div><em><%= @playspace.district.titleize %>, <%= @playspace.region.upcase %></em></div>
      <div class="playspace-address">Address: <%= @playspace.address.titleize %></div>
    </div>
    <div class="col-xs-4 col-sm-4">
      <%= link_to 'Back', playspace_path(@playspace.id), class: "btn btn-default" %>
    </div>
  </div>

  <% if current_user %>
    <div class="row">
      <div class="col-xs-12 col-sm-10 col-md-8 well">
        <%= render 'form' %>
      </div>
    </div>
  <% else %>
    <div>
      <h6><%= link_to 'Log in', login_path %> to add a review</h6>
    </div>
  <% end %>

  <div class="row">
    <div class="col-xs-12">
      <ul class="list-unstyled reviews">
        <% @reviews.each do |review| %>
          <li class="stars">
            <% review.rating.times do %>
              <span class="glyphicon glyphicon-star yellow"></span>
            <% end %>
          </li>
          <li class="comment">
            <p>
              <%= image_tag review.photo.url %>
              "<%= review.comment %>" ~ <em><%= review.user.username %></em>, <small><%= review.created_at.strftime("%d-%b-%Y") %></small>
            </p>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

</div>

<script>HideSearchToggle()</script>