config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get '/about', to: 'static_pages#about'

  resources :users, only: [:new, :index, :create]

  resources :sessions, only: [:new, :create, :destroy]
  get    'login',  to: 'sessions#new'
  delete 'logout', to: "sessions#destroy"

  resources :categories, only: [:index, :show, :new, :create] do
    resources :playspaces, only: :index
  end

  resources :playspaces, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:new, :index, :create]
  end

  resources :bookmarks, only: [:index, :create, :destroy]
end

app/views/layouts/_filter.html.erb
<!-- Sidebar right -->
<div id="sidebar-wrapper-right" class="hide">
  <ul class="sidebar-nav">
    <li class="sidebar-brand">PlaySpace</li>

    <div class="container col-xs-12">
      <%= form_for :playspace, {url: "/playspaces", method: "get", html:{id: "search"}} do |f| %>
        <div>
          <br>
          <label>Search by name:</label>
          <%= f.text_field :name %>
        </div>
        <br>
        <div>
          <%= f.select :region, ['HK','Kln','NT'], :prompt => 'Select by region:' %>
        </div>
        <br>
        <div>
          <%= f.select :district, [], :prompt => 'Select by district:'%>
        </div>
        <br>
        <div>
          <%= f.collection_select :category_id, Category.all, :id, :name, :prompt => 'Select by category:' %>
        </div>
        <br>
        <div>
          <label>Search by feature:</label>
          <div>
            <label>bike path</label>
            <%= f.check_box :bike_path, {}, true, false %>
          <div>
            <label>merry-go-round</label>
            <%= f.check_box :merry_go_round, {}, true, false  %>
          </div>
          <div>
            <label>play structure</label>
            <%= f.check_box :play_structure, {}, true, false  %>
          </div>
          <div>
            <label>seesaw</label>
            <%= f.check_box :seesaw, {}, true, false  %>
          </div>
          <div>
            <label>slide</label>
            <%= f.check_box :slide, {}, true, false  %>
          </div>
          <div>
            <label>swing</label>
            <%= f.check_box :swing, {}, true, false  %>
          </div>
          <div>
            <label>carpark</label>
            <%= f.check_box :carpark, {}, true, false  %>
          </div>
          <div>
            <label>snack shop</label>
            <%= f.check_box :snack_shop, {}, true, false  %>
          </div>
          <div>
            <label>toilet</label>
            <%= f.check_box :wc, {}, true, false  %>
          </div>
          <br>
        </div>
        <%= submit_tag 'Search', class:"btn btn-success btn-block no-margin" %>
      <% end %>
    </div>
  </ul>
</div>
<!-- /#sidebar-wrapper right-->

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button href="#menu-toggle2" id="menu-toggle2" type="button" class="navbar-toggle collapsed pull-right" aria-expanded="false" class="hide">
        <span class="sr-only">Toggle navigation</span>
        <span class="glyphicon glyphicon-search"></span>
      </button>
      <button href="#menu-toggle" id="menu-toggle" type="button" class="navbar-toggle collapsed pull-left" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div id="logo" class="center-block brand">
        <%= link_to image_tag("playspace_logo.png"), root_path %>
      </div>
    </div>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <button href="#menu-toggle3" id="menu-toggle3" type="button" aria-expanded="false" class="hide">
            <span class="sr-only">Toggle Search</span>
            <span class="glyphicon glyphicon-search"></span>
          </button>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<!-- Sidebar left -->
<div id="sidebar-wrapper">
  <ul class="sidebar-nav">
    <li class="sidebar-brand"></li>
    <li class=""><a href="/playspaces"><h4>Find a Play Space</h4></a></li>
    <li><h4><%= link_to 'About', about_path %></h4></li>

    <% if current_user %>
      <li><h4><%= link_to 'Logout', logout_path, method: :delete, data: {confirm: 'Are you sure?'} %></h4></li>
      <li><h4><%= link_to 'Add a Playspace', new_playspace_path %></h4></li>
    <% else %>
      <li><h4><%= link_to 'Sign up', new_user_path %></h4></li>
      <li><h4><%= link_to 'Login', login_path %></h4></li>
    <% end %>
  </ul>
</div>
<!-- /#sidebar-wrapper left-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PlayspaceApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- nav -->
  <%= render 'layouts/navbar' %>
  <!-- /nav -->

  <div id="wrapper">
    <!-- sidebar -->
    <%= render 'layouts/sidebar' %>
    <!-- /sidebar-->

    <!-- filter sidebar-->
    <%= render 'layouts/filter' %>
    <!--/filter sidebar-->

    <!-- Page Content -->
    <div id="test" class="page-content-wrapper">
      <div class="container-fluid">
        <div class="row">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
  <!-- /#page-content-wrapper -->
</body>

</html>